// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmjsiscfbzesjduegaem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtanNpc2NmYnplc2pkdWVnYWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3OTc5NDUsImV4cCI6MjA1ODM3Mzk0NX0.8n8E0tPG5IbS6MpD80x7QXpSRS6ICduKoQuYET0cMlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);